services:
  liferay:
    image: liferay/portal:7.4.3.132-ga132
    container_name: travelhub
    ports:
      - "8080:8080"
    environment:
      - VIRTUAL_HOST=localhost
      - LIFERAY_JAVA_OPTS=-Xmx2048m -Xms1024m
    volumes:
      - ./configs/docker/portal-ext.properties:/opt/liferay/portal-ext.properties:ro
    networks:
      - liferay-network
    restart: unless-stopped

networks:
  liferay-network:
    external: true
